import React from 'react'
import './About.css'
function About() {
    return (
        <div className="about-us-doc-container">
            <h4>About Claron</h4>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iusto iure unde consequatur mollitia dolorem illum minus reprehenderit velit qui esse tenetur possimus optio quos adipisci aliquam sed earum ut, voluptas sapiente corporis, quae voluptate laboriosam! Beatae, est! Exercitationem deleniti cumque placeat at facilis et laboriosam minima asperiores. Modi, explicabo blanditiis cum distinctio suscipit inventore quae perferendis at rerum. Officia, rerum deleniti tempora expedita aliquid architecto similique veniam quas harum adipisci ad saepe tenetur. Alias deleniti, modi eveniet porro saepe quos iusto officia! Dolore explicabo magni minima numquam expedita ipsa accusamus natus in excepturi, sed distinctio, cum quidem magnam nemo. Voluptatum temporibus quibusdam culpa ab modi, repudiandae et accusantium minus suscipit saepe illum nulla deserunt? Dolorem ipsam libero voluptate voluptatem. Rem expedita dolorum qui harum aut iste quae dignissimos! Sint, omnis dolorum. Nemo, suscipit assumenda magnam iusto quia quae iste minus fuga non sequi odio corrupti facilis facere quasi consectetur enim repellendus. Officiis, ad illum! Et, commodi? Officia explicabo, tempore magnam neque reprehenderit sapiente porro alias iste doloremque. Ipsum praesentium cumque ipsa fugit et. Eius rem distinctio aliquid quaerat cumque quo magni amet incidunt nesciunt commodi expedita recusandae delectus eum, inventore suscipit ut reiciendis nihil quia harum maxime, omnis ullam temporibus eveniet ipsa! Laborum nostrum minima praesentium ipsa velit, maiores repudiandae neque, officia, similique accusantium in itaque? Doloribus explicabo quo voluptates ex, earum, voluptatem dicta quia deserunt, atque alias blanditiis laboriosam possimus laborum totam commodi placeat? Reprehenderit, doloremque praesentium! Error esse aspernatur culpa perferendis architecto odit? Laborum tempore ullam deleniti voluptatum illo ad harum ipsa adipisci enim? Dolorum sunt fuga qui, dolorem doloribus assumenda aspernatur ipsa esse non laudantium reiciendis dolore nesciunt error optio architecto inventore autem itaque a facere? Modi expedita praesentium molestiae eum mollitia. Iure facere quae dolor aperiam eos atque, doloribus sunt aut, et deleniti ad assumenda eum?</p>
        </div>
    )
}

export default About
